name: Cyberchase Tests

on:
  push:
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run tests and calculate progress
        id: test-results
        run: |
          python tests.py > test_output.txt || true
          passed=$(grep -o 'OK' test_output.txt | wc -l)
          total=$(grep -o 'test_sql_' test_output.txt | wc -l)
          progress=$(echo "scale=2; $passed / $total" | bc)
          echo "passed=$passed" >> $GITHUB_ENV
          echo "total=$total" >> $GITHUB_ENV
          echo "progress=$progress" >> $GITHUB_ENV

      - name: Update README with progress
        run: |
          url="https://progress-bar.xyz/$(echo $progress | awk '{printf "%d", $1 * 100}')?title=$passed+из+$total"
          sed -i '/<!-- PROGRESS BAR -->/c\![Progress Bar]('"$url"')' README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add README.md
          if git diff-index --quiet HEAD; then
            echo "No changes to commit"
          else
            git commit -m "Update progress bar in README"
            git push
          fi
        
